language: python

python:
  - "3.6"

install:
  - easy_install distribute
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  - pip install codecov

script:
  - pytest --cov=app/
  - coveralls
after_success:
  - codecov
